version: '3.4'

services:
  nginx_test:
    container_name: nginx_test
    build: .
    #entrypoint: ["/bin/sh","-c","sleep infinity"]
    environment:
    - TEST_PORT=8080
    - TEST_MSG=test message!
    - TEST_BC=lightblue
    - TEST_TC=green
    restart: always
    ports:
    - 8080:8080
