version: '3.4'

services:
  nginx_test:
    container_name: nginx_test
    build: .
    #entrypoint: ["/bin/sh","-c","sleep infinity"]
    environment:
    - T1_PORT=8080
    - T1_MSG=test message!
    - T1_BC=lightblue
    - T1_TC=green
    restart: always
    ports:
    - 8080:8080
