version: '3.4'

services:
  nginx_test:
    container_name: nginx_test
    build: .
    #entrypoint: ["/bin/sh","-c","sleep infinity"]
    environment:
    - NGINX_TEST_PORT=8080
    - NGINX_TEST_MSG="test message!"
    restart: always
    ports:
    - 8080:8080
